### ISSUE TITLE
Data didn't update

### ISSUE THREAD

**Issue by impredicative** [axisbits/covid-api#5]
I don't see data for Mar 23. I don't know why. A lot of downstream users rely on this source.

**Comment by elitemaks** [comment]
@impredicative first of all, sorry for this. I posted an update in the readme file, that Johns Hopkins CSSE changed data structure, you can check it here - https://github.com/CSSEGISandData/COVID-19/issues/1250. 
Currently, we are working on the code for this new format data parsing, and we need to be sure that the structure remains the same.

New data file introduced separation by cities in the US, instead of states, as it was before. We will make sure that state-level data will remain the same and will add city-level data. All these updates will be online today.

**Comment by elitemaks** [comment]
@impredicative data is updated keeping the original structure.
Soon we will create an endpoint for getting data of US cities.

**Comment by impredicative** [comment]
I deeply appreciate the quick fix. In the future I will check the readme first.
