### ISSUE TITLE
Is it possible to add a query to include all dates by default?

### ISSUE THREAD

**Issue by absolutelysimon** [axisbits/covid-api#6]
I'd love to be able to bulk-request a country's historical data. Any chance of adding that?

Ideally some flag that allows /reports to return an array of the reports from ever day.

**Comment by elitemaks** [comment]
@absolutelysimon how do you suggest to make this request? We can have an endpoint named "historical," which will require country ISO code and will return an array of objects, where the key is "date" and value  - data for this date for the selected country. 
However, for example, China and USA data have a separation by provinces/states so that the response may be pretty large. If that's ok, we can do that.

**Comment by impredicative** [comment]
This could put a tremendous strain on the server over time for bandwidth costs.

**Comment by impredicative** [comment]
If this is implemented, then to conserve bandwidth, by default it could return data for the last seven days only.

**Comment by elitemaks** [comment]
I close this issue as we will not implement this feature, as it could cause a big load on the server.
